application: morgan-germain
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.4"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'mordjangular.settings'

handlers:
- url: /static
  static_dir: static
  expiration: '0'
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

